### ISSUE TITLE
npm start 的时候报错

### ISSUE THREAD

**Issue by lwx333921** [react-redux-antd-es6/react#4]
module.js:487
    throw err;
    ^

Error: Cannot find module 'accepts'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\zongju\react\node_modules\express\lib\request.js:16:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! duxiaodu@0.0.1 start: `webpack-dev-server --history-api-fallback --hot --inline --process --colors --port 3000`
npm ERR! Exit status 1

**Comment by duxianwei520** [comment]
现在应该没有了吧
